### ISSUE TITLE
Improve error text when the model has HETATMs

### ISSUE THREAD

**Issue by guzmanfj** [strubelab/multiprot#26]
```
multipr --chain MSTPAESSDSKSKKDFS Tense-Swissmodel.pdb GSEFRFENSAGSGATTGVADPFATSAAAAGDDDDLYN --symmetry p6 --symtemplate Tense-Swissmodel.pdb --destination ./models
Chain 1
    Modeling with ranch...
    * Ranch failed to build the chain:
      ERROR (ATOM NUMBER): atom entries in the multichain PDB do not match. Please make sure that all the chains have the same number of atoms.

Traceback (most recent call last):
  File "/home/guzmanfj/py/multiprot/env/bin/multipr", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/guzmanfj/py/multiprot/multiprot/scripts/multipr", line 20, in <module>
    model = build.run()
  File "/home/guzmanfj/py/multiprot/multiprot/builder.py", line 651, in run
    self.create_full()
  File "/home/guzmanfj/py/multiprot/multiprot/builder.py", line 573, in create_full
    models = self.call_ranch(chaini)[:self.num]
  File "/home/guzmanfj/py/multiprot/multiprot/builder.py", line 197, in call_ranch
    raise RanchError('Models not produced.')
multiprot.errors.RanchError: Models not produced.
```

**Comment by guzmanfj** [comment]
Input PDB was a homo-hexamer with a single ion atom in each chain. I think that this error message was because all HETATMs were in separate chain in the model, instead of being part of their corresponding chains.
